@startuml
hide circle

class admins{
   + UserName
   + PassWord
}

class users{
  + Id
  + UserName
  + PassWord
  + SalaryId
  + CurrentWorkTimeId
}

class salarys{
  + Id
  + HourlySalary
  + IsActive
}

class work_times{
  + Id
  + UserId
  + StartTime
  + EndTime
  + SalaryId
}

@end
