@startuml
hide members
hide circle

class トップ

class アルバイトログイン
class アルバイトメイン

class 管理者ログイン
class 管理者メイン
class アルバイト情報管理
class 月給情報管理

トップ --> アルバイトログイン
トップ --> 管理者ログイン

アルバイトログイン --> アルバイトメイン

管理者ログイン --> 管理者メイン
管理者メイン --> アルバイト情報管理
管理者メイン --> 月給情報管理

@end
